### ISSUE TITLE
[seperate]

### ISSUE THREAD

**Issue by dxp10** [JoshuaDRose/Clasp#1]
Hi friend, could you rate my repositories and I'll rate yours at the same time? Thanks!

**Comment by JoshuaDRose** [comment]
> Hi friend, could you rate my repositories and I'll rate yours at the same time? Thanks!

Hey there, @dxp10. Could you please elaborate on what you mean 'rate'? I'm not sure if you mean 'star' or 'to give feedback on'.

Kind regards,
Joshua.

**Comment by dxp10** [comment]
Oh, I'm sorry, I wrote to you already. You have already asked me a lot of interesting questions about my projects. Thank you!
